version: '3.7'


services:
  pytest-py38:
    build:
      context: .
      dockerfile: ./compose/tests/Dockerfile.py38
    image: appsurify-testbrain-cli:pytest-py38
    container_name: cli-pytest-py38
    command: poetry run pytest --junitxml=reports/results-pytest-linux-py3.8.xml -o junit_suite_name=pytest-linux-py3.8
    volumes:
      - ./:/app/data

  pytest-py39:
    build:
      context: .
      dockerfile: ./compose/tests/Dockerfile.py39
    image: appsurify-testbrain-cli:pytest-py39
    container_name: cli-pytest-py39
    command: poetry run pytest --junitxml=reports/results-pytest-linux-py3.9.xml -o junit_suite_name=pytest-linux-py3.9
    volumes:
      - ./:/app/data

  pytest-py310:
    build:
      context: .
      dockerfile: ./compose/tests/Dockerfile.py310
    image: appsurify-testbrain-cli:pytest-py310
    container_name: cli-pytest-py310
    command: poetry run pytest --junitxml=reports/results-pytest-linux-py3.10.xml -o junit_suite_name=pytest-linux-py3.10
    volumes:
      - ./:/app/data

  pytest-py311:
    build:
      context: .
      dockerfile: ./compose/tests/Dockerfile.py311
    image: appsurify-testbrain-cli:pytest-py311
    container_name: cli-pytest-py311
    command: poetry run pytest --junitxml=reports/results-pytest-linux-py3.11.xml -o junit_suite_name=pytest-linux-py3.11
    volumes:
      - ./:/app/data

  pytest-py312:
    build:
      context: .
      dockerfile: ./compose/tests/Dockerfile.py312
    image: appsurify-testbrain-cli:pytest-py312
    container_name: cli-pytest-py312
    command: poetry run pytest --junitxml=reports/results-pytest-linux-py3.12.xml -o junit_suite_name=pytest-linux-py3.12
    volumes:
      - ./:/app/data


