[tool.pytest.ini_options]
addopts = "--strict-markers"
testpaths = "tests/unit/"
python_classes = "test_*"
xdfail_strict=true
markers = ["sleepdeprived_patched_module", "masked_modules", "patched_environ", "patched_module"]
