name: "Lint"

on: [workflow_dispatch, push]

jobs:
  flake8:
    name: "flake8"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: "Set up Poetry"
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"
      - name: "Install flake8"
        run: poetry install --with dev
      - name: "Check"
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: flake8
          run: poetry run flake8 ./src/
  isort:
    name: "isort"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: "Set up Poetry"
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"
      - name: "Install isort"
        run: poetry install --with dev
      - name: "Check"
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: isort
          run: poetry run isort ./src/ --check --diff --profile black
  black:
    name: "black"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Check"
        uses: psf/black@stable
        with:
          options: --config pyproject.toml --check
          src: ./src/
# Currently use official black action and similar method disabled
#  black:
#    name: "black"
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Checkout Repository"
#        uses: actions/checkout@v3
#      - name: "Set up Python"
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.11"
#      - name: "Set up Poetry"
#        uses: abatilo/actions-poetry@v2
#        with:
#          poetry-version: "1.6.1"
#      - name: "Install black"
#        run: poetry install --with dev
#      - name: "Check"
#        run: poetry run black ./testbrain/ --check
