name: "Lint"

on: [push, pull_request]

jobs:
  flake8:
    name: "flake8"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: "Install flake8"
        run: python -m pip install flake8
      - name: "Check"
        # Pinned to v2.0.0.
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: flake8
          run: flake8 ./testbrain/
  isort:
    name: "isort"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: "Install isort"
        run: python -m pip install isort
      - name: "Check"
        # Pinned to v2.0.0.
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: isort
          run: isort ./testbrain/ --check --diff --profile black
  black:
    name: "black"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: "Install black"
        run: python -m pip install black
      - name: "Check"
        run: black ./testbrain/ --check
