name: "Testbrain"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "releases/*"
      - "development"

jobs:
  push-changes:
    name: "Push changes to server"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: "Current branch name"
        run: echo $(git branch --show-current)

      - name: "Get branch names"
        uses: tj-actions/branch-names@v2.1
        id: branch-names

      - name: Current branch name
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"
        # Outputs: "feature/test" current PR branch.

      - name: Current branch name
        if: github.event_name == 'push'
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"
        # Outputs: "main" the default branch that triggered the push event.

      - name: Get Ref brach name
        run: |
          echo "${{ steps.branch-name.outputs.ref_branch }}"
        #  Outputs: "main" for non PR branches | "1/merge" for a PR branch

      - name: Get Head Ref branch name
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ steps.branch-name.outputs.head_ref_branch }}"
        # Outputs: "feature/test" current PR branch.

      - name: Get Base Ref branch name
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ steps.branch-name.outputs.base_ref_branch }}"
        # Outputs: "main" for main <- PR branch.

      - name: "Push"
        uses: addnab/docker-run-action@v3
        with:
          image: appsurifyinc/appsurify-testbrain-cli:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            git_hash=$(git rev-parse --short "$GITHUB_SHA")
            git_branch=${GITHUB_REF#refs/heads/}
            git2testbrain push --server ${{ secrets.TESTBRAIN_SERVER }} --token ${{ secrets.TESTBRAIN_TOKEN }} --project ${{ secrets.TESTBRAIN_PROJECT }} --branch $git_branch --start $git_hash --number 100 -l DEBUG
      - name: "Upload crash dumps"
        uses: actions/upload-artifact@v3
        with:
          name: "crashdumps"
          path: ${{ github.workspace }}/.crashdumps/
          retention-days: 1
