name: "Test"

on: [push, pull_request]


jobs:
  run-pytests:
    name: Pytest on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, macOS, Windows]
        python-version: ["3.7", "3.8", "3.11"]
        poetry-version: ["1.5.1"]
        include:
          - os: Ubuntu
            image: ubuntu-latest
          - os: Windows
            image: windows-latest
          - os: macOS
            image: macos-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Set up Poetry"
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: "Install dependencies"
        run: poetry install --with test
      - name: "Run tests"
        run: poetry run pytest --exitfirst --verbose --failed-first --junitxml=reports/junit-pytest-${{ matrix.os }}-PY${{ matrix.python-version }}.xml --cov=./testbrain/ --cov-report xml:reports/coverage-pytest-${{ matrix.os }}-PY${{ matrix.python-version }}.xml
      - name: "Save reports"
        uses: actions/upload-artifact@master
        with:
          name: reports
          path: ./reports/
  publish-reports:
    if: github.event_name == 'pull_request'
    name: "Add comment to PR"
    runs-on: ubuntu-latest
    needs: [run-pytests]
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Load reports"
        uses: actions/download-artifact@master
        with:
          name: reports
          path: ./reports/
      - name: Pytest coverage report
        uses: MishaKav/pytest-coverage-comment@main
        with:
          title: Coverage Report
          junitxml-title: PyTest Summary Title
          create-new-comment: false
          multiple-files: |
            Ubuntu-PY3.7, ./reports/coverage-pytest-Ubuntu-PY3.7.xml, ./reports/junit-pytest-Ubuntu-PY3.7.xml
            Ubuntu-PY3.8, ./reports/coverage-pytest-Ubuntu-PY3.8.xml, ./reports/junit-pytest-Ubuntu-PY3.8.xml
            Ubuntu-PY3.11, ./reports/coverage-pytest-Ubuntu-PY3.11.xml, ./reports/junit-pytest-Ubuntu-PY3.11.xml
            macOS-PY3.7, ./reports/coverage-pytest-macOS-PY3.7.xml, ./reports/junit-pytest-macOS-PY3.7.xml
            macOS-PY3.8, ./reports/coverage-pytest-macOS-PY3.8.xml, ./reports/junit-pytest-macOS-PY3.8.xml
            macOS-PY3.11, ./reports/coverage-pytest-macOS-PY3.11.xml, ./reports/junit-pytest-macOS-PY3.11.xml
            Windows-PY3.7, ./reports/coverage-pytest-Windows-PY3.7.xml, ./reports/junit-pytest-Windows-PY3.7.xml
            Windows-PY3.8, ./reports/coverage-pytest-Windows-PY3.8.xml, ./reports/junit-pytest-Windows-PY3.8.xml
            Windows-PY3.11, ./reports/coverage-pytest-Windows-PY3.11.xml, ./reports/junit-pytest-Windows-PY3.11.xml
#      - name: "Pytest coverage comment"
#        uses: MishaKav/pytest-coverage-comment@main
#        with:
#          pytest-xml-coverage-path: ./reports/coverage-pytest-${{ matrix.os }}-PY${{ matrix.python-version }}.xml
#          junitxml-path: ./reports/junit-pytest-${{ matrix.os }}-PY${{ matrix.python-version }}.xml
#          unique-id-for-comment: ${{ matrix.os }}-${{ matrix.python-version }}
#          create-new-comment: false
#      - name: Pytest coverage comment multiple-files mixed 2
#        uses: MishaKav/pytest-coverage-comment@main
#        with:
#          create-new-comment: false
#          multiple-files: |
#            ${{ matrix.os }}-PY${{ matrix.python-version }}, ./reports/coverage-pytest-${{ matrix.os }}-PY${{ matrix.python-version }}.xml, ./reports/junit-pytest-${{ matrix.os }}-py${{ matrix.python-version }}.xml
#      - name: Pytest coverage comment
#        uses: MishaKav/pytest-coverage-comment@main
#        with:
#          pytest-xml-coverage-path: ./reports/coverage-pytest-${{ matrix.os }}-PY${{ matrix.python-version }}.xml
#          junitxml-path: ./reports/junit-pytest-${{ matrix.os }}-PY${{ matrix.python-version }}.xml
