name: "Test"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "development"
  push:
    branches:
      - "main"
      - "releases/*.*.*"
      - "development"

jobs:
  run-pytests:
    name: pytest on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, macOS, Windows]
        python-version: ["3.7", "3.8", "3.11"]
        poetry-version: ["1.5.1"]
        include:
          - os: Ubuntu
            image: ubuntu-latest
          - os: Windows
            image: windows-latest
          - os: macOS
            image: macos-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Set up Poetry"
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: "Install dependencies"
        run: poetry install --with test
      - name: "Run tests"
        run: poetry run pytest --exitfirst --verbose --failed-first --junitxml=junit-reports/pytest-junit-report-${{ matrix.os }}-PY${{ matrix.python-version }}.xml --cov=./src/ --cov-report xml:cov-reports/pytest-coverage-report-${{ matrix.os }}-PY${{ matrix.python-version }}.xml
      - name: "Surface failing tests"
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: junit-reports/pytest-junit-report-${{ matrix.os }}-PY${{ matrix.python-version }}.xml
          summary: true
          display-options: fEX
          fail-on-empty: false
      - name: "Upload Test Reports"
        uses: actions/upload-artifact@v3
        with:
            name: "junit-reports"
            path: ./junit-reports/
            retention-days: 1
      - name: "Upload Coverage Reports"
        uses: actions/upload-artifact@v3
        with:
            name: "cov-reports"
            path: ./cov-reports/
            retention-days: 1
