name: "Testbrain"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "releases/*"
      - "development"
      - "test-ci"

jobs:
  push-changes:
    name: "Push changes to server"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: "Push"
        uses: addnab/docker-run-action@v3
        with:
          image: appsurifyinc/appsurify-testbrain-cli:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            git2testbrain push --server ${{ env.TESTBRAIN_SERVER }} --token ${{ secrets.TESTBRAIN_TOKEN }} --project ${{ env.TESTBRAIN_PROJECT }} --branch ${{ github.ref_name }} --start ${{ github.sha }} --number 100 -l DEBUG
      - name: "Upload crash dumps"
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: "crashdumps"
          path: ${{ github.workspace }}/.crashdumps/
          retention-days: 1
